//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dminterface1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int idResponse { get; set; }
        public string Response1 { get; set; }
        public int Person_idPerson { get; set; }
        public int Questions_idQuestions { get; set; }
        public int Survey_idSurvey { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Question Question { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
